### ISSUE TITLE
Lambda

### ISSUE THREAD

**Issue by carsonwright** [mirah/mirah#287]
I'm trying to use a lambda and am having trouble compiling it, is there any way to use lambda'so yet? 
I want to convert https://github.com/carsonwright/spark-test to mirah

**Comment by carsonwright** [comment]
Is mirah active?

**Comment by baroquebobcat** [comment]
Yes. It is active. We did a release in November, and have been working on
nailing down things for another release since then.

Unfortunately, static importing single methods is unsupported right now. I
was able to get a hello world working by using your pom and doing the
following.

I created a
```
$ cat src/hello.mirah`
```

```mirah
import static spark.Spark.*

get("/hello") do |req, res|
  "Hello World"
end
```

Then I created a file containing the dependency classpath, and ran mirah
with that classpath.
```
$ mvn -Dmdep.outputFile=myClasspath dependency:build-classpath

$ mirah -cp `cat myClasspath` src/hello.mirah
[Thread-4] INFO spark.webserver.SparkServer - == Spark has ignited ...
[Thread-4] INFO spark.webserver.SparkServer - >> Listening on 0.0.0.0:4567
[Thread-4] INFO org.eclipse.jetty.server.Server - jetty-9.0.2.v20130417
[Thread-4] INFO org.eclipse.jetty.server.ServerConnector - Started
ServerConnector@6eb459e6{HTTP/1.1}{0.0.0.0:4567}
```

There's a patch for the maven plugin to bump the mirahc version to one that
supports java 8. Until that's merged / published, you can't use maven to
build and run directly. If you want to try the patched maven plugin, you
could try installing https://github.com/mirah/maven-mirah-plugin/pull/8


On Wed, Mar 18, 2015 at 7:45 AM, Carson Wright <notifications@github.com>
wrote:

> Is mirah active?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mirah/mirah/issues/287#issuecomment-82978062>.
>



-- 
-Nick Howard
http://blog.baroquebobcat.com/

**Comment by carsonwright** [comment]
Thank you very much, this project looks amazing, I'm really excited about watching what ya'll are doing.
