### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by arjunmenon** [mirah/mirah#466]
Is this project inactive? Mirah is extremely promising. It will be a shame if this is abandoned. If you have a roadmap, I will be willing to support it.

**Comment by shannah** [comment]
Mirah was started by @headius as a potential vehicle to make it easier for developers to contribute to JRuby.  His primary focus is JRuby, though.  

@baroquebobcat was doing lots of good work managing the project for quite a while, but I see that he must be busy with other things lately.

There have also been a few other active contributors over the years.

I was doing a lot of experimentation with Mirah a few years back.  Created a Netbeans plugin, and added support for Codename One.  Both of those things need some updates as Mirah was changed slightly since then - as happens with alpha projects.

Mirah works.  It is the only (non-java) JVM language that doesn't require an additional runtime library.   You can produce output with it that is completely binary-compatible with regular Java, without introducing additional dependencies.  This is very nice.  And in some projects, this may make Mirah a uniquely suitable option.  Its macro support is also quite powerful.

Mirah has enormous potential, but currently it doesn't look like there is much work going into it.  Improvements to Java itself (e.g. Lambdas) has removed some of the verbosity in Java that previously drove developers to seek alternate languages.  I think Kotlin has also filled much of the vaccuum that languages like Mirah would logically grow into.  

I haven't been able to spend much time with Mirah the past few years, either for various reasons.

Mirah still exists, and it works, and it will still be there when the time and project are right.

**Comment by sara192** [comment]
Hola

**Comment by headius** [comment]
This is not really an issue. Mirah is not currently active, mostly because I do not have time to maintain it anymore.
